# Generated by Django 5.0 on 2023-12-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200908_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
